# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#configuration
quote_style = "AutoPreferDouble"
indent_type = "Spaces"
indent_width = 2
column_width = 120
line_endings = "Unix"
call_parentheses = "None"
