-- https://www.nerdfonts.com/cheat-sheet
-- https://github.com/nvim-tree/nvim-web-devicons
local icons = {
	env = { icon = "", name = "env" },
	go = { icon = "", color = "#4285F4", name = "goextra" },
	git = { icon = "", color = "#F05032", name = "git" },
	xsl = { icon = "󰗀", color = "#E39F53", name = "xsl" },
	yaml = { icon = "󰈙", color = "#EC5F59", name = "yaml" },
	vite = { icon = "󱐋", color = "#F3B340", name = "vite" },
	astro = { icon = "", color = "#EF8547", name = "astro" },
	postcss = { icon = "", color = "#DD3A0A", name = "postcss" },
	cypress = { icon = "󰯲", color = "#69D3A7", name = "cypress" },
	test_ts = { icon = "", color = "#3178C6", name = "test_typescript" },
	test_js = { icon = "", color = "#F7DF1E", name = "test_javascript" },
	license = { icon = "", color = "#CDC058", name = "license" },
	prettier = { icon = "󰉽", color = "#F7B93E", name = "prettier" },
	changelog = { icon = "󰦖", color = "#97C15C", name = "changelog" },
	typescript = { icon = "", color = "#3178C6", name = "typescript" },
	dependabot = { icon = "", color = "#025E8C", name = "dependabot" },
}

return {
	strict = true,
	override_by_extension = {
		prettierignore = icons.prettier,
		prettierrc = icons.prettier,
		gitignore = icons.git,
		gitkeep = icons.git,
		postcss = icons.postcss,
		astro = icons.astro,
		pcss = icons.postcss,
		yaml = icons.yaml,
		yml = icons.yaml,
		xsl = icons.xsl,
		ts = icons.typescript,
		-- TODO: find a way to use two ending extensions
		--[[ ["cy.ts"] = icons.cypress,
		["cy.js"] = icons.cypress,
		["test.js"] = icons.test_js,
		["test.ts"] = icons.test_ts, ]]
	},
	override_by_filename = {
		[".nvmrc"] = { icon = "󰎙", color = "#339933", name = "nvm" },
		["log.txt"] = { icon = "", name = "log" },
		["logs.txt"] = { icon = "", name = "log" },
		["go.mod"] = icons.go,
		["go.sum"] = icons.go,
		["go.work"] = icons.go,
		["go.work.sum"] = icons.go,
		[".env.sample"] = icons.env,
		[".env.local"] = icons.env,
		["license.md"] = icons.license,
		["license.txt"] = icons.license,
		["changelog.md"] = icons.changelog,
		["changelog.txt"] = icons.changelog,
		["dependabot.yml"] = icons.dependabot,
		["readme.md"] = { icon = "󰋼", color = "#5EA3EF", name = "readme" },
		[".tmux.conf"] = { icon = "", color = "#1BB91F", name = "tmux" },
		["vercel.json"] = { icon = "󰔶", color = "#FFFFFF", name = "vercel" },
		["netlify.toml"] = { icon = "", color = "#00C7B7", name = "netlify" },
		-- vite ts
		["vite.config.ts"] = icons.vite,
		["vitest.config.ts"] = icons.vite,
		["vitest.config.mts"] = icons.vite,
		["vitest.config.cts"] = icons.vite,
		-- vite js
		["vite.config.js"] = icons.vite,
		["vitest.config.js"] = icons.vite,
		["vitest.config.mjs"] = icons.vite,
		["vitest.config.cjs"] = icons.vite,
		["astro.config.mjs"] = icons.astro,
		["astro.config.ts"] = icons.astro,
		["postcss.config.js"] = icons.postcss,
		["postcss.config.mjs"] = icons.postcss,
		["postcss.config.cjs"] = icons.postcss,
		["cypress.config.ts"] = icons.cypress,
		["cypress.config.js"] = icons.cypress,
		["ads.txt"] = { icon = "󰲇", color = "#4285F4", name = "GoogleAds" },
		["todo.md"] = { icon = "", color = "#A6E3A1", name = "todo" },
		["yarn.lock"] = { icon = "", color = "#2C8EBB", name = "yarn" },
		["robots.txt"] = { icon = "󰚩", color = "#F38BA8", name = "robots" },
		["cargo.toml"] = { icon = "", color = "#D24933", name = "cargo.toml" },
		["jsconfig.json"] = { icon = "", color = "#F7DF1E", name = "jsconfig" },
		["pnpm-lock.yaml"] = { icon = "󰛷", color = "#F69220", name = "pnpm-lock.yaml" },
		["playwright.config.ts"] = { icon = "󰴂", color = "#2EAD33", name = "playwright" },
		-- TODO: overrides for entrypoint filenames
		-- ["init.lua"] = { icon = "", color = "#B2CFE5", name = "init.lua" },
	},
}
