---@desc  inspired by material icon theme
--- https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/main/images/folderIcons.png
--- https://www.nerdfonts.com/cheat-sheet
--- https://wasm.simpleicons.org
local icons = {
	tabby = "󰄛",
	["tabby-client"] = "󰄛",
	npm = "",
	nvm = "󰎙",
	desktop = "",
	document = "󱧶",
	bun = "󰳮",
	movie = "󰎁",
	book = "",
	store = "󰓜",
	footer = "󰛻",
	header = "󰛼",
	navbar = "󰛼",
	applications = "",
	trash = "",
	volume = "󰋊",
	library = "",
	command = "",
	cypress = "󰯲",
	scraper = "󱇪",
	script = "󰯂",
	style = "",
	route = "󰑪",
	mail = "",
	home = "󱂵",
	e2e = "󰕥",
	cmd = "",
	app = "󱂵",
	doc = "󱂷",
	lib = "󰌱",
	upload = "󰉙",
	download = "󰉍",
	key = "󰢬",
	token = "󰢬",
	layout = "󰕮",
	middleware = "󰽞",
	lang = "󰗊",
	language = "󰗊",
	environment = "",
	icon = "󰚝",
	admin = "󰉐",
	auth = "󰉐",
	secure = "󰉐",
	animation = "󰗘",
	audio = "󰎆",
	core = "",
	-- util
	util = "󱁿",
	utility = "󱁿",
	utilities = "󱁿",
	web = "󰖟",
	www = "󰖟",
	public = "󰖟",
	global = "󰖟",
	static = "󰖟",
	schema = "󱋣",
	model = "󱋣",
	mdx = "",
	markdown = "",
	misc = "",
	-- public = "󱞊",
	info = "󱂷",
	content = "󰣞",
	fonts = "",
	goal = "",
	target = "",
	nvim = "",
	-- target = "󰩷",
	--
	robot = "󰚩",
	debug = "",
	test = "",
	-- test = "󰙨",
	temp = "󰪺",
	tmp = "󰪺",
	event = "󰂚",
	-- operating systems
	ios = "",
	macos = "",
	linux = "",
	window = "",
	android = "",
	design = "󰏘",
	note = "",
	board = "",
	article = "󱔗",
	resource = "󱔗",
	calendar = "",
	weekly = "",
	theme = "󰏘",
	color = "󰏘",
	error = "󰷌",
	cache = "󰪺",
	pkg = "󰏓",
	package = "󰏓",
	usr = "",
	user = "",
	users = "",
	storybook = "󰂺",
	github = "",
	workflow = "",
	git = "",
	vscode = "󰨞",
	vite = "󱐋",
	common = "󱁽",
	other = "󱁽",
	client = "󰦉",
	backend = "󰒋",
	frontend = "󰦉",
	ui = "󰦉",
	mobile = "",
	constant = "",
	i18n = "󰗊",
	ci = "󰴋",
	generator = "󰴋",
	generated = "󰴋",
	generate = "󰴋",
	component = "󰀻",
	node_modules = "",
	pnpm = "",
	dist = "",
	build = "",
	bin = "",
	release = "",
	template = "",
	views = "",
	src = "",
	hook = "󰛢",
	context = "",
	log = "",
	kubernetes = "󱃾",
	page = "󱧶",
	import = "󰉗",
	include = "󰉗",
	-- images
	assets = "󰉏",
	images = "󰉏",
	media = "󰉏",
	-- configs
	conf = "",
	config = "",
	plugin = "󰐱",
	ext = "",
	extension = "",
	guard = "󰦝",
	coverage = "󰕥",
	project = "",
	json = "",
	share = "",
	private = "󱧴",
	python = "",
	money = "",
	-- server
	api = "󰒍",
	server = "󰒋",
	homelab = "󰒋",
	serverless = "󰊕",
	["function"] = "󰊕",
	-- db
	database = "󰆼",
	data = "󰆼",
	db = "󰆼",
	-- languages
	types = "",
	["react-dom"] = "󰜈",
	tailwindcss = "󱏿",
	c = "",
	go = "",
	ts = "󰛦",
	js = "",
	cpp = "",
	next = "󰰓",
	webpack = "󰜫",
	obsidian = "󱥐",
	javascript = "",
	typescript = "󰛦",
	postcss = "",
	ssh = "",
	tmux = "",
	vim = "",
	music = "󱍙",
	picture = "󰉏",
	video = "󰕧",
	haskell = "",
	mongodb = "",
	eslint = "󰱺",
	docker = "󰡨",
	svelte = "",
	["svelte-kit"] = "",
	astro = "",
	react = "󰜈",
	java = "",
	rust = "",
	cargo = "",
	rustup = "",
	sass = "󰟬",
	html = "",
	vue = "",
	svg = "󰜡",
	css = "",
	lua = "",
	sql = "󰆼",
	youtube = "󰗃",
	srandle = "",
}

return {
	---return the icon associated with a name removing the first character last character and a combination of the both
	---@param name string
	---@return string
	get_icon = function(name)
		name = string.lower(name)
		local last_element = string.len(name) - 1
		local name_without_first_char = string.sub(name, 2)
		local name_without_last_char = string.sub(name, 1, last_element)
		local name_without_ending_chars = string.sub(name, 2, last_element)
		local name_without_ending_two_chars = string.sub(name, 3, string.len(name) - 2)
		return icons[name]
			or icons[name_without_first_char]
			or icons[name_without_last_char]
			or icons[name_without_ending_chars]
			or icons[name_without_ending_two_chars]
	end,
}
