type Devicon = { color?: string; icon: string; name?: string };
type DeviconMap = Record<string, Devicon>;

const icons = {
	ai: { color: "white", icon: "", name: "copilot" },
	archive: { color: "#B0B447", icon: "", name: "archive" },
	astro: { color: "#EF8547", icon: "", name: "astro" },
	auto: { color: "#C12C1F", icon: "󱎫", name: "auto" },
	babel: { color: "#F9DC3E", icon: "", name: "babel" },
	changelog: { color: "#97C15C", icon: "󰦖", name: "changelog" },
	codecov: { color: "#F01F7A", icon: "", name: "codecov" },
	codeowners: { color: "#B0B447", icon: "󰪋", name: "codeowners" },
	commitlint: { color: "#429488", icon: "󰜘", name: "commitlint" },
	cspell: { color: "#A62C17", icon: "", name: "cspell" },
	cypress: { color: "#69D3A7", icon: "󰯲", name: "cypress" },
	dependabot: { color: "#025E8C", icon: "", name: "dependabot" },
	env: { icon: "", name: "env" },
	eslintrc: { icon: "󰱺", name: "eslintrc" },
	gatsby: { color: "#663399", icon: "󰹃", name: "gatsby" },
	gemini: { color: "#4880F5", icon: "󰪁", name: "gemini" },
	git: { color: "#F05032", icon: "", name: "git" },
	go: { color: "#4DA9BE", icon: "", name: "go" },
	goextra: { color: "#DA4F7A", icon: "", name: "goextra" },
	graphql: { color: "#E10098", icon: "", name: "graphql" },
	javascript: { color: "#F7DF1E", icon: "󰌞", name: "javascript" },
	knip: { color: "#F56E0F", icon: "", name: "knip" },
	lefthook: { color: "#FF1E1E", icon: "", name: "lefthook" },
	license: { color: "#CDC058", icon: "", name: "license" },
	lighthouse: { color: "#F44B21", icon: "󰧿", name: "lighthouse" },
	lintstaged: { color: "#FF0000", icon: "", name: "lintstaged" },
	log: { icon: "", name: "log" },
	next: { color: "#FFFFFF", icon: "󰰓", name: "next" },
	nginx: { color: "#009639", icon: "", name: "nginx" },
	node_version: { color: "#339933", icon: "󰎙", name: "nvm" },
	nx: { color: "#FFFFFF", icon: "󱢴", name: "nx" },
	oxc: { color: "#FF915C", icon: "󰡾", name: "oxc" },
	php: { color: "#777BB4", icon: "", name: "php" },
	postcss: { color: "#DD3A0A", icon: "󰁣", name: "postcss" },
	prettier: { color: "#5F87FF", icon: "", name: "prettier" },
	python: { color: "#3776AB", icon: "", name: "python" },
	routes: { color: "#007808", icon: "󰑪", name: "routes" },
	rss: { color: "#FFA500", icon: "", name: "rss" },
	sitemap: { icon: "", name: "sitemap" },
	storybook: { color: "#FF4785", icon: "󰂺", name: "storybook" },
	stylelint: { icon: "", name: "stylelint" },
	test_js: { color: "#F7DF1E", icon: "", name: "test_javascript" },
	test_ts: { color: "#3178C6", icon: "", name: "test_typescript" },
	typescript: { color: "#3178C6", icon: "", name: "typescript" },
	unlighthouse: { color: "#A286FC", icon: "󰧿", name: "unlighthouse" },
	vite: { color: "#9135FF", icon: "󱐋", name: "vite" },
	vitest: { color: "#00FF74", icon: "󰸞", name: "vitest" },
	wrangler: { color: "#F38020", icon: "", name: "cloudflare" },
	xsl: { color: "#E39F53", icon: "󰗀", name: "xsl" },
	yaml: { color: "#EC5F59", icon: "󰈙", name: "yaml" },
	yarn: { color: "#2C8EBB", icon: "", name: "yarn" },
} as const satisfies DeviconMap;

export const override_by_extension = {
	"7z": icons.archive,
	"asm": { icon: "" },
	"astro": icons.astro,
	"babelrc.cjs": icons.babel,
	"babelrc.cts": icons.babel,
	"babelrc.js": icons.babel,
	"babelrc.json": icons.babel,
	"babelrc.mjs": icons.babel,
	"cjs": icons.javascript,
	"code-profile": { color: "#007ACC", icon: "󰨞", name: "vscode" },
	"cy.js": icons.cypress,
	"cy.ts": icons.cypress,
	"d.ts": { color: "#3178C6", icon: "", name: "ts_definition" },
	"dmg": icons.archive,
	"gitconfig": icons.git,
	"gitignore": icons.git,
	"gitignore_global": icons.git,
	"gitkeep": icons.git,
	"go": icons.go,
	"gql": icons.graphql,
	"graphql": icons.graphql,
	"graphqlrc": icons.graphql,
	"graphqlrc.js": icons.graphql,
	"graphqlrc.json": icons.graphql,
	"graphqlrc.toml": icons.graphql,
	"graphqlrc.ts": icons.graphql,
	"graphqlrc.yaml": icons.graphql,
	"graphqlrc.yml": icons.graphql,
	"Jenkinsfile": { color: "white", icon: "", name: "jenkins" },
	"js": icons.javascript,
	"jsonc": { color: "#FFF000", icon: "󰘦", name: "jsonc" },
	"mjs": icons.javascript,
	"mts": icons.typescript,
	"njk": { color: "#1C4913", icon: "", name: "nunjucks" },
	"pcss": icons.postcss,
	"php": icons.php,
	"postcss": icons.postcss,
	"prettierignore": icons.prettier,
	"prettierrc": icons.prettier,
	"pug": { color: "#A86454", icon: "", name: "pug" },
	"stories.js": icons.storybook,
	"stories.jsx": icons.storybook,
	"stories.ts": icons.storybook,
	"stories.tsx": icons.storybook,
	"tar.gz": icons.archive,
	"ts": icons.typescript,
	"xcf": { icon: "", name: "gimp" },
	"xsl": icons.xsl,
	"yaml": icons.yaml,
	"yml": icons.yaml,
	"zip": icons.archive,
} as const satisfies DeviconMap;

export const override_by_filename = {
	".autorc": icons.auto,
	".autorc.js": icons.auto,
	".autorc.json": icons.auto,
	".autorc.ts": icons.auto,
	".autorc.yaml": icons.auto,
	".autorc.yml": icons.auto,
	".babelrc": icons.babel,
	".codecov.yaml": icons.codecov,
	".codecov.yml": icons.codecov,
	".commitlintrc": icons.commitlint,
	".commitlintrc.cjs": icons.commitlint,
	".commitlintrc.cts": icons.commitlint,
	".commitlintrc.js": icons.commitlint,
	".commitlintrc.json": icons.commitlint,
	".commitlintrc.mjs": icons.commitlint,
	".commitlintrc.ts": icons.commitlint,
	".commitlintrc.yaml": icons.commitlint,
	".commitlintrc.yml": icons.commitlint,
	".cSpell.json": icons.cspell,
	".cspell.json": icons.cspell,
	".env.example": icons.env,
	".env.local": icons.env,
	".env.production": icons.env,
	".env.sample": icons.env,
	".eslintrc.cjs": icons.eslintrc,
	".eslintrc.js": icons.eslintrc,
	".eslintrc.json": icons.eslintrc,
	".knip.json": icons.knip,
	".knip.jsonc": icons.knip,
	".lighthouserc.cjs": icons.lighthouse,
	".lighthouserc.js": icons.lighthouse,
	".lighthouserc.json": icons.lighthouse,
	".lighthouserc.yaml": icons.lighthouse,
	".lighthouserc.yml": icons.lighthouse,
	".lintstagedrc": icons.lintstaged,
	".lintstagedrc.cjs": icons.lintstaged,
	".lintstagedrc.cts": icons.lintstaged,
	".lintstagedrc.js": icons.lintstaged,
	".lintstagedrc.json": icons.lintstaged,
	".lintstagedrc.mjs": icons.lintstaged,
	".lintstagedrc.mts": icons.lintstaged,
	".lintstagedrc.ts": icons.lintstaged,
	".lintstagedrc.yaml": icons.lintstaged,
	".lintstagedrc.yml": icons.lintstaged,
	".node-version": icons.node_version,
	".nvmrc": icons.node_version,
	".oxfmtrc.json": icons.oxc,
	".oxfmtrc.jsonc": icons.oxc,
	".oxlintrc.json": icons.oxc,
	".oxlintrc.jsonc": icons.oxc,
	".prettierrc.cts": icons.prettier,
	".prettierrc.mts": icons.prettier,
	".prettierrc.ts": icons.prettier,
	".python-version": icons.python,
	".stow-local-ignore": { icon: "" },
	".stylelintrc": icons.stylelint,
	".stylelintrc.cjs": icons.stylelint,
	".stylelintrc.js": icons.stylelint,
	".stylelintrc.json": icons.stylelint,
	".stylelintrc.mjs": icons.stylelint,
	".tmux.conf": { color: "#1BB91F", icon: "", name: "tmux" },
	".viminfo": { color: "#019733", icon: "", name: "vim" },
	".yarnrc": icons.yarn,
	"_redirects": { icon: "" },
	"ads.txt": { color: "#4285F4", icon: "󰲇", name: "GoogleAds" },
	"AGENTS.md": icons.ai,
	"amplify.yml": { icon: "󰸏" },
	"artisan": { color: "#FF2D20", icon: "󰫐", name: "laravel" },
	"astro.config.mjs": icons.astro,
	"astro.config.ts": icons.astro,
	"authors.md": { ...icons.codeowners, color: "#E15241" },
	"auto.config.js": icons.auto,
	"auto.config.mjs": icons.auto,
	"auto.config.mts": icons.auto,
	"auto.config.ts": icons.auto,
	"babel.config.cjs": icons.babel,
	"babel.config.cts": icons.babel,
	"babel.config.js": icons.babel,
	"babel.config.json": icons.babel,
	"babel.config.mjs": icons.babel,
	"bacon.toml": { color: "#C12C1F", icon: "", name: "bacon" },
	"Brewfile": { color: "#FBB040", icon: "", name: "Brewfile" },
	"cargo.toml": { color: "#D24933", icon: "", name: "cargo.toml" },
	"changelog.md": icons.changelog,
	"changelog.txt": icons.changelog,
	"ci.config.json": { color: "#89b4fa", icon: "", name: "monorepoci" },
	"codecov.yaml": icons.codecov,
	"codecov.yml": icons.codecov,
	"CODEOWNERS": icons.codeowners,
	"commitlintrc.js": icons.commitlint,
	"commitlintrc.ts": icons.commitlint,
	"contributing.md": { color: "#F7CC4F", icon: "󰅍", name: "contributing" },
	"CRUSH.md": { ...icons.ai, color: "#FFB6C1" },
	"cspell.config.cjs": icons.cspell,
	"cspell.config.js": icons.cspell,
	"cspell.config.json": icons.cspell,
	"cspell.config.yaml": icons.cspell,
	"cspell.config.yml": icons.cspell,
	"cSpell.json": icons.cspell,
	"cspell.json": icons.cspell,
	"cspell.yaml": icons.cspell,
	"cspell.yml": icons.cspell,
	"cypress.config.js": icons.cypress,
	"cypress.config.ts": icons.cypress,
	"dependabot.yml": icons.dependabot,
	"electron-flags.conf": { color: "#47848F", icon: "", name: "electron" },
	"eslint.config.cjs": icons.eslintrc,
	"eslint.config.cts": icons.eslintrc,
	"eslint.config.js": icons.eslintrc,
	"eslint.config.mjs": icons.eslintrc,
	"eslint.config.mts": icons.eslintrc,
	"eslint.config.ts": icons.eslintrc,
	"extensions.json": { color: "#C59F46", icon: "", name: "extensions" },
	"ffmpeg.txt": { color: "#007808", icon: "", name: "ffmpeg" },
	"FUNDING.yml": { color: "#DF6B92", icon: "", name: "funding" },
	"gatsby-browser.js": icons.gatsby,
	"gatsby-config.js": icons.gatsby,
	"gatsby-ssr.js": icons.gatsby,
	"GEMINI.md": icons.gemini,
	"gemini.md": icons.gemini,
	"go.mod": icons.goextra,
	"go.sum": icons.goextra,
	"go.work": icons.goextra,
	"go.work.sum": icons.goextra,
	"graphql.config.js": icons.graphql,
	"graphql.config.json": icons.graphql,
	"graphql.config.toml": icons.graphql,
	"graphql.config.ts": icons.graphql,
	"install": { color: "#FF2D20", icon: "󰇚", name: "install" },
	"jsconfig.json": { color: "#F7DF1E", icon: "", name: "jsconfig" },
	"knip.config.js": icons.knip,
	"knip.config.ts": icons.knip,
	"knip.js": icons.knip,
	"knip.json": icons.knip,
	"knip.jsonc": icons.knip,
	"knip.ts": icons.knip,
	"launch.json": { color: "#C59F46", icon: "", name: "launch" },
	"lazy-lock.json": { color: "#457BE2", icon: "󰒲", name: "lazy" },
	"lefthook.json": icons.lefthook,
	"lefthook.jsonc": icons.lefthook,
	"lefthook.toml": icons.lefthook,
	"lefthook.yaml": icons.lefthook,
	"lefthook.yml": icons.lefthook,
	"license.md": icons.license,
	"license.txt": icons.license,
	"lighthouserc.cjs": icons.lighthouse,
	"lighthouserc.js": icons.lighthouse,
	"lighthouserc.json": icons.lighthouse,
	"lighthouserc.yaml": icons.lighthouse,
	"lighthouserc.yml": icons.lighthouse,
	"lint-staged.config.js": icons.lintstaged,
	"lint-staged.config.ts": icons.lintstaged,
	"log.txt": icons.log,
	"logs.txt": icons.log,
	"netlify.toml": { color: "#00C7B7", icon: "", name: "netlify" },
	"next.config.js": icons.next,
	"next.config.mjs": icons.next,
	"next.config.ts": icons.next,
	"nodemon.json": { color: "#76D04B", icon: "", name: "nodemon" },
	"nvim-pack-lock.json": { color: "#57A143", icon: "", name: "nvim" },
	"nx.json": icons.nx,
	"phpunit.xml": icons.php,
	"playwright.config.ts": { color: "#2EAD33", icon: "󰴂", name: "playwright" },
	"pnpm-lock.yaml": { color: "#F69220", icon: "󰛷", name: "pnpm-lock.yaml" },
	"pnpm-workspace.yaml": {
		color: "#FFFFFF",
		icon: "󰛷",
		name: "pnpm-workspace.yaml",
	},
	"postcss.config.cjs": icons.postcss,
	"postcss.config.js": icons.postcss,
	"postcss.config.mjs": icons.postcss,
	"prettier.config.js": icons.prettier,
	"project.json": icons.nx,
	"readme.md": { color: "#5EA3EF", icon: "󰋼", name: "readme" },
	"robots.txt": { color: "#F38BA8", icon: "󰚩", name: "robots" },
	"routes.js": icons.routes,
	"routes.jsx": icons.routes,
	"routes.ts": icons.routes,
	"routes.tsx": icons.routes,
	"rss.xml": icons.rss,
	"rss.xml.js": icons.rss,
	"rss.xml.ts": icons.rss,
	"sitemap.xml": icons.sitemap,
	"sitemap.xml.js": icons.sitemap,
	"sitemap.xml.ts": icons.sitemap,
	"starship.toml": { color: "#D73167", icon: "", name: "Starship" },
	"stylelint.config.cjs": icons.stylelint,
	"stylelint.config.mjs": icons.stylelint,
	"todo.md": { color: "#A6E3A1", icon: "", name: "todo" },
	"tsconfig.base.json": icons.typescript,
	"turbo.json": { color: "#FF1E56", icon: "󱪂", name: "turborepo" },
	"typedoc.json": { color: "#891AF6", icon: "󰫄", name: "typedoc" },
	"unlighthouse.config.js": icons.unlighthouse,
	"unlighthouse.config.ts": icons.unlighthouse,
	"vercel.json": { color: "#FFFFFF", icon: "󰔶", name: "vercel" },
	"vite.config.js": icons.vite,
	"vite.config.ts": icons.vite,
	"vite.workspace.ts": icons.vite,
	"vitest.config.cjs": icons.vitest,
	"vitest.config.cts": icons.vitest,
	"vitest.config.js": icons.vitest,
	"vitest.config.mjs": icons.vitest,
	"vitest.config.mts": icons.vitest,
	"vitest.config.ts": icons.vitest,
	"vitest.workspace.mts": icons.vitest,
	"vitest.workspace.ts": icons.vitest,
	"wrangler.json": icons.wrangler,
	"wrangler.jsonc": icons.wrangler,
	"wrangler.toml": icons.wrangler,
	"yarn.lock": icons.yarn,
} as const satisfies DeviconMap;

export const strict = true;
