type Devicon = { icon: string; name?: string; color?: string };
type DeviconMap = Record<string, Devicon>;

const icons = {
	env: { icon: "", name: "env" },
	sitemap: { icon: "", name: "sitemap" },
	eslintrc: { icon: "󰱺", name: "eslintrc" },
	stylelint: { icon: "", name: "stylelint" },
	ai: { icon: "", color: "white", name: "copilot" },
	go: { icon: "", color: "#4DA9BE", name: "go" },
	nx: { icon: "󱢴", color: "#FFFFFF", name: "nx" },
	git: { icon: "", color: "#F05032", name: "git" },
	php: { icon: "", color: "#777BB4", name: "php" },
	rss: { icon: "", color: "#FFA500", name: "rss" },
	oxc: { icon: "󰡾", color: "#FF915C", name: "oxc" },
	xsl: { icon: "󰗀", color: "#E39F53", name: "xsl" },
	auto: { icon: "󱎫", color: "#C12C1F", name: "auto" },
	knip: { icon: "", name: "knip", color: "#F56E0F" },
	yarn: { icon: "", color: "#2C8EBB", name: "yarn" },
	next: { icon: "󰰓", color: "#FFFFFF", name: "next" },
	vite: { icon: "󱐋", color: "#F3B340", name: "vite" },
	yaml: { icon: "󰈙", color: "#EC5F59", name: "yaml" },
	astro: { icon: "", color: "#EF8547", name: "astro" },
	babel: { icon: "", color: "#F9DC3E", name: "babel" },
	cspell: { icon: "", color: "#A62C17", name: "cspell" },
	gatsby: { icon: "󰹃", color: "#663399", name: "gatsby" },
	gemini: { icon: "󰪁", color: "#4880F5", name: "gemini" },
	routes: { icon: "󰑪", color: "#007808", name: "routes" },
	archive: { icon: "", color: "#B0B447", name: "archive" },
	codecov: { icon: "", color: "#F01F7A", name: "codecov" },
	goextra: { icon: "", color: "#DA4F7A", name: "goextra" },
	graphql: { icon: "", color: "#E10098", name: "graphql" },
	license: { icon: "", color: "#CDC058", name: "license" },
	cypress: { icon: "󰯲", color: "#69D3A7", name: "cypress" },
	postcss: { icon: "󰁣", color: "#DD3A0A", name: "postcss" },
	prettier: { icon: "", color: "#5F87FF", name: "prettier" },
	wrangler: { icon: "", color: "#F38020", name: "cloudflare" },
	changelog: { icon: "󰦖", color: "#97C15C", name: "changelog" },
	storybook: { icon: "󰂺", color: "#FF4785", name: "storybook" },
	dependabot: { icon: "", color: "#025E8C", name: "dependabot" },
	lintstaged: { icon: "", name: "lintstaged", color: "#FF0000" },
	typescript: { icon: "", color: "#3178C6", name: "typescript" },
	codeowners: { icon: "󰪋", name: "codeowners", color: "#B0B447" },
	commitlint: { icon: "󰜘", color: "#429488", name: "commitlint" },
	javascript: { icon: "󰌞", color: "#F7DF1E", name: "javascript" },
	test_js: { icon: "", color: "#F7DF1E", name: "test_javascript" },
	test_ts: { icon: "", color: "#3178C6", name: "test_typescript" },
	unlighthouse: { icon: "󰧿", color: "#F44B21", name: "unlighthouse" },
} satisfies DeviconMap;

export const override_by_extension = {
	"7z": icons.archive,
	"Jenkinsfile": { icon: "", name: "jenkins", color: "white" },
	"asm": { icon: "" },
	"astro": icons.astro,
	"babelrc.cjs": icons.babel,
	"babelrc.cts": icons.babel,
	"babelrc.js": icons.babel,
	"babelrc.json": icons.babel,
	"babelrc.mjs": icons.babel,
	"cjs": icons.javascript,
	"code-profile": { icon: "󰨞", color: "#007ACC", name: "vscode" },
	"cy.js": icons.cypress,
	"cy.ts": icons.cypress,
	"d.ts": { icon: "", color: "#3178C6", name: "ts_definition" },
	"dmg": icons.archive,
	"gitconfig": icons.git,
	"gitignore": icons.git,
	"gitignore_global": icons.git,
	"gitkeep": icons.git,
	"go": icons.go,
	"gql": icons.graphql,
	"graphql": icons.graphql,
	"graphqlrc": icons.graphql,
	"graphqlrc.js": icons.graphql,
	"graphqlrc.json": icons.graphql,
	"graphqlrc.toml": icons.graphql,
	"graphqlrc.ts": icons.graphql,
	"graphqlrc.yaml": icons.graphql,
	"graphqlrc.yml": icons.graphql,
	"js": icons.javascript,
	"jsonc": { icon: "󰘦", color: "#FFF000", name: "jsonc" },
	"mjs": icons.javascript,
	"mts": icons.typescript,
	"njk": { icon: "", color: "#1C4913", name: "nunjucks" },
	"pcss": icons.postcss,
	"php": icons.php,
	"postcss": icons.postcss,
	"prettierignore": icons.prettier,
	"prettierrc": icons.prettier,
	"pug": { icon: "", color: "#A86454", name: "pug" },
	"stories.js": icons.storybook,
	"stories.jsx": icons.storybook,
	"stories.ts": icons.storybook,
	"stories.tsx": icons.storybook,
	"tar.gz": icons.archive,
	"ts": icons.typescript,
	"xcf": { icon: "", name: "gimp" },
	"xsl": icons.xsl,
	"yaml": icons.yaml,
	"yml": icons.yaml,
	"zip": icons.archive,
} satisfies DeviconMap;

export const override_by_filename = {
	".babelrc": icons.babel,
	".cSpell.json": icons.cspell,
	".codecov.yaml": icons.codecov,
	".codecov.yml": icons.codecov,
	".commitlintrc": icons.commitlint,
	".autorc": icons.auto,
	".autorc.js": icons.auto,
	".autorc.json": icons.auto,
	".autorc.ts": icons.auto,
	".autorc.yaml": icons.auto,
	".autorc.yml": icons.auto,
	"auto.config.js": icons.auto,
	"auto.config.ts": icons.auto,
	"auto.config.mjs": icons.auto,
	"auto.config.mts": icons.auto,
	".commitlintrc.cjs": icons.commitlint,
	".commitlintrc.cts": icons.commitlint,
	".commitlintrc.js": icons.commitlint,
	".commitlintrc.json": icons.commitlint,
	".commitlintrc.mjs": icons.commitlint,
	".commitlintrc.ts": icons.commitlint,
	".commitlintrc.yaml": icons.commitlint,
	".commitlintrc.yml": icons.commitlint,
	".cspell.json": icons.cspell,
	".env.example": icons.env,
	".env.local": icons.env,
	".env.production": icons.env,
	".env.sample": icons.env,
	".eslintrc.cjs": icons.eslintrc,
	".eslintrc.js": icons.eslintrc,
	".eslintrc.json": icons.eslintrc,
	".knip.json": icons.knip,
	".knip.jsonc": icons.knip,
	".nvmrc": { icon: "󰎙", color: "#339933", name: "nvm" },
	".oxfmtrc.json": icons.oxc,
	".oxfmtrc.jsonc": icons.oxc,
	".oxlintrc.json": icons.oxc,
	".oxlintrc.jsonc": icons.oxc,
	".stow-local-ignore": { icon: "" },
	".stylelintrc": icons.stylelint,
	".stylelintrc.cjs": icons.stylelint,
	".stylelintrc.js": icons.stylelint,
	".stylelintrc.json": icons.stylelint,
	".stylelintrc.mjs": icons.stylelint,
	".tmux.conf": { icon: "", color: "#1BB91F", name: "tmux" },
	".viminfo": { icon: "", color: "#019733", name: "vim" },
	".yarnrc": icons.yarn,
	"AGENTS.md": icons.ai,
	"Brewfile": { icon: "", color: "#FBB040", name: "Brewfile" },
	"CODEOWNERS": icons.codeowners,
	"CRUSH.md": { ...icons.ai, color: "#FFB6C1" },
	"FUNDING.yml": { icon: "", color: "#DF6B92", name: "funding" },
	"GEMINI.md": icons.gemini,
	"_redirects": { icon: "" },
	"ads.txt": { icon: "󰲇", color: "#4285F4", name: "GoogleAds" },
	"amplify.yml": { icon: "󰸏" },
	"artisan": { icon: "󰫐", color: "#FF2D20", name: "laravel" },
	"astro.config.mjs": icons.astro,
	"astro.config.ts": icons.astro,
	"authors.md": { ...icons.codeowners, color: "#E15241" },
	"babel.config.cjs": icons.babel,
	"babel.config.cts": icons.babel,
	"babel.config.js": icons.babel,
	"babel.config.json": icons.babel,
	"babel.config.mjs": icons.babel,
	"cSpell.json": icons.cspell,
	"cargo.toml": { icon: "", color: "#D24933", name: "cargo.toml" },
	"changelog.md": icons.changelog,
	"changelog.txt": icons.changelog,
	"ci.config.json": { icon: "", color: "#89b4fa", name: "monorepoci" },
	"codecov.yaml": icons.codecov,
	"codecov.yml": icons.codecov,
	"commitlintrc.js": icons.commitlint,
	"commitlintrc.ts": icons.commitlint,
	"contributing.md": { icon: "󰅍", color: "#F7CC4F", name: "contributing" },
	"cspell.config.cjs": icons.cspell,
	"cspell.config.js": icons.cspell,
	"cspell.config.json": icons.cspell,
	"cspell.config.yaml": icons.cspell,
	"cspell.config.yml": icons.cspell,
	"cspell.json": icons.cspell,
	"cspell.yaml": icons.cspell,
	"cspell.yml": icons.cspell,
	"cypress.config.js": icons.cypress,
	"cypress.config.ts": icons.cypress,
	"dependabot.yml": icons.dependabot,
	"electron-flags.conf": { icon: "", color: "#47848F", name: "electron" },
	"routes.js": icons.routes,
	"routes.jsx": icons.routes,
	"routes.tsx": icons.routes,
	"routes.ts": icons.routes,
	"eslint.config.cjs": icons.eslintrc,
	"eslint.config.cts": icons.eslintrc,
	"eslint.config.js": icons.eslintrc,
	"eslint.config.mjs": icons.eslintrc,
	"eslint.config.mts": icons.eslintrc,
	"eslint.config.ts": icons.eslintrc,
	"extensions.json": { icon: "", color: "#C59F46", name: "extensions" },
	"ffmpeg.txt": { icon: "", color: "#007808", name: "ffmpeg" },
	"gatsby-browser.js": icons.gatsby,
	"gatsby-config.js": icons.gatsby,
	"gatsby-ssr.js": icons.gatsby,
	"gemini.md": icons.gemini,
	"go.mod": icons.goextra,
	"go.sum": icons.goextra,
	"go.work": icons.goextra,
	"go.work.sum": icons.goextra,
	"graphql.config.js": icons.graphql,
	"graphql.config.json": icons.graphql,
	"graphql.config.toml": icons.graphql,
	"graphql.config.ts": icons.graphql,
	"install": { icon: "󰇚", color: "#FF2D20", name: "install" },
	"jsconfig.json": { icon: "", color: "#F7DF1E", name: "jsconfig" },
	"knip.config.js": icons.knip,
	"knip.config.ts": icons.knip,
	"knip.js": icons.knip,
	"knip.json": icons.knip,
	"knip.jsonc": icons.knip,
	"knip.ts": icons.knip,
	".lintstagedrc.mjs": icons.lintstaged,
	".lintstagedrc.cjs": icons.lintstaged,
	".lintstagedrc.js": icons.lintstaged,
	"lint-staged.config.js": icons.lintstaged,
	".lintstagedrc": icons.lintstaged,
	".lintstagedrc.json": icons.lintstaged,
	".lintstagedrc.yaml": icons.lintstaged,
	".lintstagedrc.yml": icons.lintstaged,
	"launch.json": { icon: "", color: "#C59F46", name: "launch" },
	"lazy-lock.json": { icon: "󰒲", color: "#457BE2", name: "lazy" },
	"license.md": icons.license,
	"license.txt": icons.license,
	"log.txt": { icon: "", name: "log" },
	"logs.txt": { icon: "", name: "log" },
	"netlify.toml": { icon: "", color: "#00C7B7", name: "netlify" },
	"next.config.js": icons.next,
	"next.config.mjs": icons.next,
	"next.config.ts": icons.next,
	"nodemon.json": { icon: "", color: "#76D04B", name: "nodemon" },
	"nx.json": icons.nx,
	"phpunit.xml": icons.php,
	"playwright.config.ts": { icon: "󰴂", color: "#2EAD33", name: "playwright" },
	"pnpm-lock.yaml": { icon: "󰛷", color: "#F69220", name: "pnpm-lock.yaml" },
	"pnpm-workspace.yaml": {
		icon: "󰛷",
		color: "#FFFFFF",
		name: "pnpm-workspace.yaml",
	},
	"postcss.config.cjs": icons.postcss,
	"postcss.config.js": icons.postcss,
	"postcss.config.mjs": icons.postcss,
	"prettier.config.js": icons.prettier,
	".prettierrc.ts": icons.prettier,
	".prettierrc.cts": icons.prettier,
	".prettierrc.mts": icons.prettier,
	"project.json": icons.nx,
	"readme.md": { icon: "󰋼", color: "#5EA3EF", name: "readme" },
	"robots.txt": { icon: "󰚩", color: "#F38BA8", name: "robots" },
	"rss.xml": icons.rss,
	"rss.xml.js": icons.rss,
	"rss.xml.ts": icons.rss,
	"sitemap.xml": icons.sitemap,
	"sitemap.xml.js": icons.sitemap,
	"sitemap.xml.ts": icons.sitemap,
	"starship.toml": { icon: "", color: "#D73167", name: "Starship" },
	"stylelint.config.cjs": icons.stylelint,
	"stylelint.config.mjs": icons.stylelint,
	"todo.md": { icon: "", color: "#A6E3A1", name: "todo" },
	"tsconfig.base.json": icons.typescript,
	"turbo.json": { icon: "󱪂", color: "#FF1E56", name: "turborepo" },
	"unlighthouse.config.js": icons.unlighthouse,
	"unlighthouse.config.ts": icons.unlighthouse,
	"vercel.json": { icon: "󰔶", color: "#FFFFFF", name: "vercel" },
	"vite.config.js": icons.vite,
	"vite.config.ts": icons.vite,
	"vite.workspace.ts": icons.vite,
	"vitest.config.cjs": icons.vite,
	"vitest.config.cts": icons.vite,
	"vitest.config.js": icons.vite,
	"vitest.config.mjs": icons.vite,
	"vitest.config.mts": icons.vite,
	"vitest.config.ts": icons.vite,
	"vitest.workspace.mts": icons.vite,
	"vitest.workspace.ts": icons.vite,
	"wrangler.json": icons.wrangler,
	"wrangler.jsonc": icons.wrangler,
	"wrangler.toml": icons.wrangler,
	"yarn.lock": icons.yarn,
} satisfies DeviconMap;

export const strict = true;
