--- https://www.nerdfonts.com/cheat-sheet
--- https://wasm.simpleicons.org
return {
	packageJSON = { up_to_date = "|  ", outdated = "|  " },
	telescope = { prompt_prefix = "   " },
	mason = {
		package_pending = "󰶻",
		package_installed = "󰄴",
		package_uninstalled = "󰅘",
	},
	lazy = {
		ft = "",
		lazy = "󰂠 ",
		loaded = "",
		not_loaded = "",
	},
	cmp = {
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Enum = " ",
		EnumMember = " ",
		Field = "󰄶 ",
		File = " ",
		Folder = " ",
		Function = "󰊕 ",
		Interface = "󰜰",
		Keyword = "󰌆 ",
		Method = "ƒ ",
		Module = "󰏗 ",
		Property = " ",
		Snippet = "󰘍 ",
		Struct = " ",
		Text = " ",
		Unit = " ",
		Value = "󰎠 ",
		Variable = " ",
	},
}
