return {
	neotree = require("configs.icons.neo-tree-icons"),
	cmp = {
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Enum = " ",
		EnumMember = " ",
		Field = "󰄶 ",
		File = " ",
		Folder = " ",
		Function = "󰊕 ",
		Interface = "󰜰",
		Keyword = "󰌆 ",
		Method = "ƒ ",
		Module = "󰏗 ",
		Property = " ",
		Snippet = "󰘍 ",
		Struct = " ",
		Text = " ",
		Unit = " ",
		Value = "󰎠 ",
		Variable = " ",
	},
	lazy = {
		ft = "",
		lazy = "󰂠 ",
		loaded = "",
		not_loaded = "",
	},
	telescope = {
		prompt_prefix = "   ",
	},
}
